config/routes.rb
Rails.application.routes.draw do
  resources :announcements do
    resources :comments
  end
  devise_for :users

  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    get '/users/password', to: 'devise/passwords#new'
  end

  get 'overview', to:'static#overview', as: :overview
  get 'safety', to:'static#safety', as: :safety
  
  root to: 'static#overview'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)  
    user ||= User.new
    if user.admin?
        can :manage, :all
    else
        can :read, Announcement
        can :create, Comment
        can :destroy, Comment, user_id: user.id
    end
  end
end

app/models/announcement.rb
class Announcement < ApplicationRecord

  is_impressionable
  
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates_presence_of :title, :body, :image_link
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :announcement

  validates_presence_of :body
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :trackable

  validates_presence_of :name, :contact_number
  has_many :announcements
  has_many :comments
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController

  impressionist :actions=>[:show]
  load_and_authorize_resource
  
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [ :edit, :update, :destroy]

  def index
    @announcements = Announcement.all.order('created_at DESC')
  end

  def show
    @comment = Comment.new
    @comments = @announcement.comments.order('created_at DESC')

    impressionist @announcement
  end

  def new
    @announcement = current_user.announcements.build
  end

  def edit
  end

  def create
    @announcement = current_user.announcements.build(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully posted' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully removed' }
      format.json { head :no_content }
    end
  end

  private
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    def announcement_params
      params.require(:announcement).permit(:title, :image_link, :body, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :contact_number, :password, :password_confirmation])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :contact_number, :password, :password_confirmation])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	before_action :set_announcement
	before_action :authenticate_user!, only:[:create, :destroy]
	
	def create
		@comment = @announcement.comments.new(comment_params)
		@comment.user = current_user
		@comment.save
		redirect_back(fallback_location: root_path)
	end

	def destroy
		@comment = @announcement.comments.find(params[:id])
		@comment_id = @comment.id
		@comment.destroy
	end

	private
	def comment_params
		params.require(:comment).permit(:body, :announcement_id)
	end
	def set_announcement
		@announcement = Announcement.find(params[:announcement_id])
	end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def overview
  end

  def safety
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/announcements/_form.html.erb
<section class="mt-5">
  <%= simple_form_for(@announcement,:class=>"flex flex-col") do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    <div class="mb-6 pt-3 rounded bg-gray-200">
      <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="email">Title</label>
      <%= f.input :title, label: false, input_html:{class:"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3"} %>
    </div>
    <div class="mb-6 pt-3 rounded bg-gray-200">
      <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="email">Image Link</label>
      <%= f.input :image_link, label: false, input_html:{class:"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3"} %>
    </div>
    <div class="mb-6 pt-3 rounded bg-gray-200">
      <label class="block text-gray-700 text-sm font-bold mb-2 ml-3" for="email">Body</label>
      <%= f.input :body, label: false, input_html:{class:"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3"} %>
    </div>

    <%= f.association :user, as: :hidden %>

    <%= f.button :submit,:class=>"bg-purple-600 hover:bg-purple-700 text-white font-bold px-3 py-3 rounded shadow-lg hover:shadow-xl transition duration-200"%>
  <% end %>
</section>

app/views/announcements/edit.html.erb
<% provide(:page_title, "Announcements") %>
<% provide(:announcement_active, "active") %>

<% if user_signed_in? %>
    <%= render 'shared/navbar_user' %>
<% else %>
    <%= render 'shared/navbar_public' %>
<% end %>

<div class="md:flex md:flex-col md:justify-center md:items-center md:mt-20">
  <main class="bg-white w-auto mx-4 px-4 py-4 md:p-12 my-10 rounded-lg shadow-2xl mt-32 md:w-2/5">
   <section>
      <p class="text-gray-600 pt-2">
      <%= link_to announcements_path do %>
        <i class="fas fa-angle-left"></i>
      <% end %>
      Update Announcement
      </p>
   </section>
	<%= render 'form', announcement: @announcement %>
</main>
</div>

app/views/announcements/index.html.erb
<% provide(:page_title, "Announcements") %>
<% provide(:announcement_active, "active") %>

<% if user_signed_in? %>
    <%= render 'shared/navbar_user' %>
<% else %>
    <%= render 'shared/navbar_public' %>
<% end %>

<div class="mt-20 md:flex md:flex-col md:justify-center md:items-center md:mt-20">
  <div class="w-auto mx-4 py-1 my-2 md:w-4/5 md:py-2">
    <% if can? :create, @announcement %>
      <%= link_to new_announcement_path, :class=>"px-2 py-1 bg-green-600 rounded text-green-100" do %>
        <i class="fas fa-bullhorn mr-1"></i> New Announcement
      <% end %>
    <% end %>
  </div>
</div>

<div class="md:flex md:flex-col md:justify-center md:items-center">
<% @announcements.each do |announcement| %>
  <main class=" bg-white w-auto mx-4 p-2 md:p-4 my-4 rounded-lg shadow-2xl md:w-4/5 md:my-2 md:text-lg">
    <div class="text-gray-400 text-xs"><%= announcement.created_at.strftime("%B, %d, %Y")%></div>
    <%= link_to announcement.title, announcement %>
    <div class="text-gray-400 text-xs pt-2 ">
      <span><i class="far fa-eye"></i> <%= announcement.impressionist_count(:filter=>:ip_address) %></span>
      <span><i class="far fa-comment pl-2"></i> <%= announcement.comments.count%></span>
      <span><i class="far fa-clock pl-2"></i> <%= time_ago_in_words(announcement.created_at)%></span>
    </div>
  </main>
<% end %>
</div>

app/views/announcements/new.html.erb
<% provide(:page_title, "Announcements") %>
<% provide(:announcement_active, "active") %>

<% if user_signed_in? %>
    <%= render 'shared/navbar_user' %>
<% else %>
    <%= render 'shared/navbar_public' %>
<% end %>

<div class="md:flex md:flex-col md:justify-center md:items-center md:mt-20">
  <main class="bg-white w-auto mx-4 px-4 py-4 md:p-12 my-10 rounded-lg shadow-2xl mt-32 md:w-2/5">
    <section>
        <p class="text-gray-600 pt-2">
        <%= link_to announcements_path do %>
          <i class="fas fa-angle-left"></i>
        <% end %>
        Create a new Announcement
        </p>
    </section>
    <%= render 'form', announcement: @announcement %>
  </main>
</div>

app/views/announcements/show.html.erb
<% provide(:page_title, "Announcements") %>
<% provide(:announcement_active, "active") %>

<% if user_signed_in? %>
    <%= render 'shared/navbar_user' %>
<% else %>
    <%= render 'shared/navbar_public' %>
<% end %>

<div class="md:flex md:flex-col md:justify-center md:items-center md:mt-12">
<main class="bg-white max-w-6xl mx-4 p-8 md:p-12 my-2 rounded-lg shadow-2xl pt-6 mt-20">
  <div class="text-center">
    <%= image_tag(@announcement.image_link, :class=>"inline-block rounded-full h-40 w-40 shadow-lg")%>
  </div>
  <div class="mb-3 pt-3 text-center">
    <%= @announcement.title %>
  </div>
  <div class="mb-1 pt-3">
    <div class="text-xs text-gray-400"><%= @announcement.created_at.strftime("%B, %d, %Y")%></div>
  </div>
  <div class="mb-3 pt-1">
    <div class="text-justify"><%= @announcement.body %></div>
  </div>

  <div>
    <%= link_to 'Back', announcements_path(@announcement),:class=>"bg-gray-600 px-2 py-1 text-gray-50 rounded shadow text-sm" %>

    <% if can? :update, @announcement %>
      <%= link_to 'Edit', edit_announcement_path(@announcement),:class=>"bg-blue-600 px-2 py-1 text-gray-50 rounded shadow text-sm" %>
    <% end %>

    <% if can? :destroy, @announcement %>
      <%= link_to 'Delete', announcement_path,:class=>"modal-open bg-red-400 px-2 py-1 text-gray-50 rounded shadow text-sm" %>
    <% end %>

    <% if can? :create, @announcement %>
      <%= link_to 'New', new_announcement_path,:class=>"bg-purple-600 px-2 py-1 text-gray-50 rounded shadow text-sm" %>
    <% end %>
  </div>
</main>
</div>


<div class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
    <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
    
    <div class="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded shadow-lg z-50 overflow-y-auto">
      
      <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-white text-sm z-50">
        <svg class="fill-current text-white" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
          <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
        </svg>
        <span class="text-sm">(Esc)</span>
      </div>

      <!-- Add margin if you want to see some of the overlay behind the modal-->
      <div class="modal-content py-4 text-left px-6">
        <!--Title-->
        <div class="flex justify-between items-center pb-3">
          <p class="text-2xl font-bold">Attention</p>
          <div class="modal-close cursor-pointer z-50">
            <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
              <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
            </svg>
          </div>
        </div>

        <!--Body-->
        <p>Are you sure to remove this announcement?</p>
        <p>Besides the announcement, all the associated comments will be removed too. It can not be done.</p>

        <!--Footer-->
        <div class="flex justify-end pt-2">
          <%= link_to "Delete",announcement_path,method: :delete, :class=>"px-4 bg-transparent p-3 rounded-lg text-indigo-500 hover:bg-gray-100 hover:text-indigo-400 mr-2" %>
          <button class="modal-close px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400">Close</button>
        </div>
        
      </div>
    </div>
  </div>

<div class="md:flex md:flex-col md:justify-center md:items-center">
<% if @announcement.comments.count < 1 %>
  <main class="bg-white w-auto mx-4 p-4 md:p-4 my-2 md:w-3/5 rounded-lg shadow-2xl pt-6 mt-2 border-l-8 border-red-400">
    <div class="text-xs text-gray-600">There is no comment found for this announcement!</div>
  </main>
<% end %>
</div>

<!--------------------Comments------------------->
  <div class="post-comments">
      <% @comments.each do |comment| %>
        <div id="comment_pane">
          <%= render 'comments/comment', comment: comment %>
        </div>
      <% end %>
  </div>


<% if user_signed_in? %>
<!--------------------- Comment Form ------------>
<div class="md:flex md:flex-col md:justify-center md:items-center">
  <div class="bg-white w-auto mx-4 px-4 py-1 my-2 md:w-3/5 md:py-2 rounded-lg shadow-2xl">
    <div class="text-gray-400 text-xs py-3">Add your comment</div>
    <%= form_with model: [@announcement, @comment],:class=>"flex flex-col", remote: true do |f| %>
      <%= f.text_area :body, label: false, rows: 8, class:"bg-gray-200 rounded w-full text-gray-700 focus:outline-none border-b-4 border-gray-300 focus:border-purple-600 transition duration-500 px-3 pb-3" %>

        <div class="text-left" style="padding-top: 5px">
          <%= f.submit "Comment",:class=>"bg-purple-600 hover:bg-purple-700 text-white font-bold px-3 py-1 rounded shadow-lg hover:shadow-xl transition duration-200", remote: true %>
        </div>
    <% end %>
  </div>
</div>
<% end %>

<script>
    var openmodal = document.querySelectorAll('.modal-open')
    for (var i = 0; i < openmodal.length; i++) {
      openmodal[i].addEventListener('click', function(event){
    	event.preventDefault()
    	toggleModal()
      })
    }
    
    const overlay = document.querySelector('.modal-overlay')
    overlay.addEventListener('click', toggleModal)
    
    var closemodal = document.querySelectorAll('.modal-close')
    for (var i = 0; i < closemodal.length; i++) {
      closemodal[i].addEventListener('click', toggleModal)
    }
    
    document.onkeydown = function(evt) {
      evt = evt || window.event
      var isEscape = false
      if ("key" in evt) {
    	isEscape = (evt.key === "Escape" || evt.key === "Esc")
      } else {
    	isEscape = (evt.keyCode === 27)
      }
      if (isEscape && document.body.classList.contains('modal-active')) {
    	toggleModal()
      }
    };
    
    
    function toggleModal () {
      const body = document.querySelector('body')
      const modal = document.querySelector('.modal')
      modal.classList.toggle('opacity-0')
      modal.classList.toggle('pointer-events-none')
      body.classList.toggle('modal-active')
    }
  </script>

app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>">
<main class="bg-white max-w-6xl mx-auto px-12 py-8 my-2 rounded-lg shadow-2xl border-l-8 border-green-500">
	<div class="flex justify-between">
		<div>
			<span class="font-semibold text-sm text-gray-500 justify-items-start">
				<%= comment.user.name %>
			</span>
		</div>

		<div>
			<% if user_signed_in? %>
				<% if current_user && current_user == comment.user || current_user.admin? %>
					<span class="bg-red-400 px-2 text-gray-50 rounded inline-block">
						<%= link_to "Delete", announcement_comment_path(@announcement, comment), method: :delete, remote: true,:class=>"btn btn-sm btn-danger"%>
					</span>
				<% end %>
			<% end %>
		</div>
	</div>
	<span class="text-gray-400 text-xs"><i class="far fa-clock pr-1"></i><%= time_ago_in_words(comment.created_at) %> ago</span>
	<p class="text-justify"><%= comment.body %></p>
</main>
</div>

app/views/comments/create.js.erb
#('#comment_pane').prepend("<%= j render @comment %>");
#('#comment_body').val(' ');

app/views/comments/destroy.js.erb
  
$('#comment-<%= @comment_id %>').html('');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UPSI > Corona-Tracker | <%= yield(:page_title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('covid.png')%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
  </head>
  <body>
    <%= render 'shared/alert' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% if notice %>
    <div id="notice_wrapper">
        <p class="notice">
            <%= notice %>
        </p>
    </div>
<% elsif alert %>
    <div id="notice_wrapper">
        <p class="alert">
            <%= alert %>
        </p>
    </div>
<% end %>

app/views/shared/_navbar_public.html.erb
<nav class="flex items-center justify-between flex-wrap bg-gray-900 py-4 px-6 fixed w-full z-10 top-0 shadow-lg">
	<div class="flex items-center flex-shrink-0 text-white mr-6">
		<%= link_to image_tag('covid.png', :class=>"h-8 w-8"), root_path%>
		<%= link_to "UPSI Corona Tracker", root_path, :class=>"text-green-100 font-semibold text-lg px-3 no-underline hover:text-white hover:no-underline"%>
	</div>

	<div class="block lg:hidden">
		<button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-green-600 border-green-600 focus:outline-none">
			<svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
		</button>
	</div>

	<div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">
		<ul class="list-reset lg:flex justify-end flex-1 items-center">
			<li class="mr-3">
				<%= link_to "Overview", overview_path, :class=>"#{yield(:overview_active)} inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "Announcement", announcements_path, :class=>"#{yield(:announcement_active)} inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "Safety", safety_path, :class=>"#{yield(:safety_active)} inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "https://www.facebook.com/UPSIMalaysia", :class=>"inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4", :target=>"_blank" do %>
					<i class="fab fa-facebook-f"></i>
				<% end %>
			</li>
			<li class="mr-3">
				<%= link_to "https://www.instagram.com/upsi_malaysia/", :class=>"inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4", :target=>"_blank" do %>
					<i class="fab fa-instagram"></i>
				<% end %>
			</li>
			<li class="mr-3">
				<%= link_to "https://twitter.com/UPSI_Malaysia", :class=>"inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4", :target=>"_blank" do %>
					<i class="fab fa-twitter"></i>
				<% end %>
			</li>
			<li class="mr-3">
				<%= link_to "Login", new_user_session_path, :class=>"block my-1 text-green-100 border-2 border-green-600 shadow rounded no-underline hover:text-gray-200 hover:bg-green-600 py-1 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "Sign Up", new_user_registration_path, :class=>"block my-1 text-green-100 border-2 border-green-600 shadow rounded no-underline hover:text-gray-200 hover:bg-green-600 py-1 px-4"%>
			</li>
		</ul>
	</div>
</nav>

<script>
	document.getElementById('nav-toggle').onclick = function(){
		document.getElementById("nav-content").classList.toggle("hidden");
	}
</script>

app/views/shared/_navbar_user.html.erb
<nav class="flex items-center justify-between flex-wrap bg-gray-900 py-4 px-6 fixed w-full z-10 top-0 shadow-lg">
	<div class="flex items-center flex-shrink-0 text-white mr-6">
		<%= link_to image_tag('covid.png', :class=>"h-8 w-8"), root_path%>
		<%= link_to "UPSI Corona Tracker", root_path, :class=>"text-green-100 font-semibold text-lg px-3 no-underline hover:text-white hover:no-underline"%>
	</div>

	<div class="block lg:hidden">
		<button id="nav-toggle" class="flex items-center px-3 py-2 border rounded text-green-600 border-green-600 focus:outline-none">
			<svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
		</button>
	</div>

	<div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block pt-6 lg:pt-0" id="nav-content">
		<ul class="list-reset lg:flex justify-end flex-1 items-center">
			<li class="mr-3">
				<%= link_to "Overview", overview_path, :class=>"#{yield(:overview_active)} inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "Announcement", announcements_path, :class=>"#{yield(:announcement_active)} inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "Safety", safety_path, :class=>"#{yield(:safety_active)} inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "https://www.facebook.com/UPSIMalaysia", :class=>"inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4", :target=>"_blank" do %>
					<i class="fab fa-facebook-f"></i>
				<% end %>
			</li>
			<li class="mr-3">
				<%= link_to "https://www.instagram.com/upsi_malaysia/", :class=>"inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4", :target=>"_blank" do %>
					<i class="fab fa-instagram"></i>
				<% end %>
			</li>
			<li class="mr-3">
				<%= link_to "https://twitter.com/UPSI_Malaysia", :class=>"inline-block font-semibold text-gray-600 no-underline hover:text-gray-200 hover:text-underline py-2 px-4", :target=>"_blank" do %>
					<i class="fab fa-twitter"></i>
				<% end %>
			</li>
			<li class="mr-3">
				<%= link_to "My Account", edit_user_registration_path, :class=>"block my-1 font-semibold text-green-100 border-2 border-green-600 shadow rounded no-underline hover:text-gray-200 hover:bg-green-600 py-1 px-4"%>
			</li>
			<li class="mr-3">
				<%= link_to "Log-Out", destroy_user_session_path, method: :delete, :class=>"block my-1 font-semibold text-green-100 border-2 border-green-600 shadow rounded no-underline hover:text-gray-200 hover:bg-green-600 py-1 px-4"%>
			</li>
		</ul>
	</div>
</nav>

<script>
	document.getElementById('nav-toggle').onclick = function(){
		document.getElementById("nav-content").classList.toggle("hidden");
	}
</script>